version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  checkout-service:
    image: checkoutservice:latest
    ports:
      - "3001:3001"

  order-service:
    image: orderservice:latest
    ports:
      - "3000:3000"
    depends_on:
      - checkout-service
      - mongo
    environment:
      CHECKOUT_URL: 'http://checkout-service:3001'
      MONGO_URL: "mongodb://mongo:27017/orders"
